# -*- coding: utf-8 -*-
"""BeautifulSoup.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HB8NvPpXPNpf6byVbP1vktH2Clp70Z00
"""

import requests

url = 'https://www.genie.co.kr/chart/top200'
header_info = {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.102 Safari/537.36 Edge/18.19582'}
page = requests.get(url, headers = header_info)
page = page.text

from bs4 import BeautifulSoup

soup = BeautifulSoup(page, 'html.parser')

top50_songs = soup.find_all('a', class_ = 'title ellipsis')

top50_songs[29]

top50_songs_list = list()

for each_data in top50_songs :
  song_name = each_data.text
  song_name = song_name.strip()
  top50_songs_list.append(song_name)

print(top50_songs_list)
print(len(top50_songs_list))