# -*- coding: utf-8 -*-
"""CHALLENGE.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UHRhz9-Ha9jBqR8xBFiYo84bFxMcXxeX
"""

!pip install selenium
!apt-get update
!apt install chromium-chromedriver
!pip install konlpy# 국문 전처리

import time
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import Select, WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from bs4 import BeautifulSoup

specific_options = webdriver.ChromeOptions()
specific_options.add_argument('--headless')
specific_options.add_argument('--no-sandbox')
driver = webdriver.Chrome('chromedriver',options = specific_options)

driver.get('http://info.nec.go.kr/main/showDocument.xhtml?electionId=0000000000&topMenuId=EP&secondMenuId=EPEI01')
time.sleep(1)

xx ='//*[@id="electionType2"]'#국회의원선거
x = driver.find_element(By.XPATH, xx)
x.click()
time.sleep(1)

en_box = driver.find_element(By.NAME,'electionName')#조회조전
en_box.send_keys('21대')

ec_box = driver.find_element(By.NAME,'electionCode')
ec_box.send_keys('국회희원선거')

cc_box = driver.find_element(By.NAME,'cityCode')
cc_box.send_keys('강원도')

bb =' //*[@id="searchBtn"]'
b= driver.find_element(By.XPATH,bb)#검색
b.click()
time.sleep(1)

city = input()
print(city)