# -*- coding: utf-8 -*-
"""Untitled7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1W5kOVgaBO6rMtz3mJ9aqSsHGL2sOn8fB
"""

score = input()
score = int(score)

if (score>=90):
  print('A')
elif (score>=80):
  print('b')
else:
  print('c')