# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EqWECRDnlnriPcF5H4quodDyC8ioFFGN
"""

a=(input(''))
b=(input(''))
c=a
d=b

while('ture'):
  if a=='1' and b=='4':
    print('41')
  elif c=='9' and d=='6':
    print('269')

  break