# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1N6nsWKJDPvFwMszOFEJ5Q0Y9UDwjWOEW
"""

import requests
import bs4

URL = 'https://m.dhlottery.co.kr/gameResult.do?method=allWin'

raw = requests.get(URL)

html = bs4.BeautifulSoup(raw.text, 'html.parser')


target = html.find('select', "class": 'wrap_select')
#print(target)

num= target.find_all("td")
num_list = list()

for num in num_list :
    print(" ", num.text)

print(num_list)