# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nXUaYbOokQwWY9P5nKRG8C2_9zBPmO7T
"""

articles = ['대선 후보 전략 분석','경제 위기 신호 감지','주식 시장 혼란 전략','대선 여론 조사 역전 조사 결과 분석']

from sklearn.feature_extraction.text import CountVectorizer
vector = CountVectorizer()
print(vector.fit_transform(articles).toarray())
print(vector.vocabulary_)

from sklearn.feature_extraction.text import TfidfVectorizer
tf_idf = TfidfVectorizer().fit(articles)
tf_idf_matrix = tf_idf.transform(articles).toarray()
print(tf_idf_matrix)
print(tf_idf.vocabulary_)

from sklearn.metrics.pairwise import cosine_similarity

similar_article = cosine_similarity(tf_idf_matrix, tf_idf_matrix)
print(similar_article)