# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KafyDk5kPZUuZBe467jh0-W2qWr3i9o6
"""

import requests
from bs4 import BeautifulSoup

url = 'https://info.korea.ac.kr/info/community/circle.do'
header_info = {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.102 Safari/537.36 Edge/18.19582'}
page = requests.get(url, headers = header_info)
page = page.text
soup = BeautifulSoup(page, 'html.parser')

club_info = soup.find_all('h4')
club_info