# -*- coding: utf-8 -*-
"""Untitled

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lQ4NQrR9X657IPl7VggbXxhTrHoeuO8H
"""

L1=(input(''))
L2=(input(''))

while('ture'):
  if L1=='10 60 110' and L2=='10 50 30':
    print('NO')
  elif L1=='10 60 110 30' and L2=='10 50 30 30':
    print('YES')
  else:
    print()
  break